import { useEffect, useMemo, useState } from "react";
import { formatCurrency } from "../../utils/currency";
import {
  createDirectDebit, createExpense, createPayout, createSupplierCreditTransaction,
  DIRECT_DEBIT_FREQUENCIES, EXPENSE_CATEGORIES, INVOICE_OPTIONS, loadDirectDebits,
  loadExpenses, loadPayouts, loadSupplierCredit, loadSuppliers, PAYMENT_TYPES,
  PAYOUT_CATEGORIES, PAYOUT_STATUSES,
} from "../../services/expenses";

const today=()=>new Date().toISOString().slice(0,10);
const user=()=>{try{return JSON.parse(localStorage.getItem("loggedInUser")||localStorage.getItem("fairchoice_user")||"null")||{}}catch{return{}}};
const field="w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm";
const tabs=["Expenses","Payout","Direct Debit","Supplier Credit"];
function Pager({rows,page,setPage}){const pages=Math.max(1,Math.ceil(rows.length/30));return <div className="flex items-center justify-end gap-2 p-3 text-sm"><button disabled={page<=1} onClick={()=>setPage(page-1)} className="rounded border px-3 py-1 disabled:opacity-40">Previous</button><span>Page {page} of {pages}</span><button disabled={page>=pages} onClick={()=>setPage(page+1)} className="rounded border px-3 py-1 disabled:opacity-40">Next</button></div>}
function Table({headers,rows,render,page,setPage,empty="No records found."}){const slice=rows.slice((page-1)*30,page*30);return <div className="overflow-hidden rounded-xl border bg-white"><div className="overflow-x-auto"><table className="min-w-full text-xs"><thead className="bg-slate-100"><tr>{headers.map(h=><th key={h} className="p-2 text-left">{h}</th>)}</tr></thead><tbody>{slice.map(render)}{!slice.length&&<tr><td colSpan={headers.length} className="p-6 text-center text-slate-500">{empty}</td></tr>}</tbody></table></div><Pager rows={rows} page={page} setPage={setPage}/></div>}
export default function Expenses(){
 const [tab,setTab]=useState("Expenses"),[suppliers,setSuppliers]=useState([]),[expenses,setExpenses]=useState([]),[payouts,setPayouts]=useState([]),[debits,setDebits]=useState([]),[credit,setCredit]=useState({transactions:[],balance:0}),[supplierId,setSupplierId]=useState("");
 const [search,setSearch]=useState(""),[filter,setFilter]=useState("All"),[page,setPage]=useState(1),[error,setError]=useState("");
 const [ef,setEf]=useState({date:today(),type:"Fuel",other:"",amount:"",invoice:"Online",pay:"Cash",note:"",reference:""});
 const [pf,setPf]=useState({date:today(),type:"Wages",pay:"Bank",name:"",supplierId:"",period:"",note:"",amount:"",status:"Paid"});
 const [df,setDf]=useState({name:"",supplierId:"",amount:"",frequency:"Monthly",nextDueDate:today(),pay:"Bank",accountReference:"",whatsappNumber:"",reminderDaysBefore:"1",notes:""});
 const [cf,setCf]=useState({date:today(),type:"Credit Purchase",amount:"",invoiceNumber:"",pay:"Bank",reference:"",notes:""});
 async function refresh(){setError("");try{const [s,e,p,d]=await Promise.all([loadSuppliers(),loadExpenses(),loadPayouts(),loadDirectDebits()]);setSuppliers(s);setExpenses(e);setPayouts(p);setDebits(d);if(supplierId)setCredit(await loadSupplierCredit(supplierId));}catch(e){setError(e.message||"Could not load accounts information.")}}
 useEffect(()=>{refresh()},[]); useEffect(()=>{setPage(1)},[tab,search,filter]);
 async function save(fn,reset){try{await fn();reset();await refresh();alert("Saved successfully.")}catch(e){alert(e.message||"Could not save.")}}
 async function chooseSupplier(id){setSupplierId(id);setCredit(await loadSupplierCredit(id));}
 const selected=suppliers.find(s=>String(s.id)===String(supplierId));
 const expenseRows=useMemo(()=>expenses.filter(r=>(filter==="All"||r.category===filter)&&`${r.category} ${r.description} ${r.reference||""} ${r.created_by||""}`.toLowerCase().includes(search.toLowerCase())),[expenses,filter,search]);
 const payoutRows=useMemo(()=>payouts.filter(r=>(filter==="All"||r.status===filter)&&`${r.payout_type} ${r.payee_name||""} ${r.suppliers?.supplier_name||""} ${r.pay_period||""}`.toLowerCase().includes(search.toLowerCase())),[payouts,filter,search]);
 return <div className="min-h-screen bg-slate-100 p-4"><div className="mx-auto max-w-7xl space-y-4"><div><h2 className="text-2xl font-extrabold">Accounts</h2><p className="text-sm text-slate-600">Expenses, payouts, direct debit reminders and supplier credit.</p></div>{error&&<div className="rounded border border-red-300 bg-red-50 p-3 text-red-700">{error}</div>}
 <div className="grid grid-cols-2 gap-2 md:grid-cols-4">{tabs.map(t=><button key={t} onClick={()=>{setTab(t);setFilter("All")}} className={`rounded-lg border border-blue-600 px-3 py-3 font-bold ${tab===t?"bg-blue-700 text-white":"bg-white text-blue-700"}`}>{t}</button>)}</div>
 {tab==="Expenses"&&<><form onSubmit={e=>{e.preventDefault();save(()=>createExpense({expenseDate:ef.date,category:ef.type,otherReason:ef.other,amount:ef.amount,invoiceOption:ef.invoice,paymentType:ef.pay,notes:ef.note,reference:ef.reference},user()),()=>setEf({...ef,amount:"",other:"",note:"",reference:""}))}} className="rounded-xl border bg-white p-4"><h3 className="mb-3 font-bold">Record Expense</h3><div className="grid gap-3 md:grid-cols-4"><Input label="Date" type="date" v={ef.date} set={v=>setEf({...ef,date:v})}/><Select label="Expense Type" v={ef.type} set={v=>setEf({...ef,type:v})} options={EXPENSE_CATEGORIES}/>{ef.type==="Other"&&<Input label="Reason" v={ef.other} set={v=>setEf({...ef,other:v})}/>}<Input label="Amount" type="number" v={ef.amount} set={v=>setEf({...ef,amount:v})}/><Select label="Invoice" v={ef.invoice} set={v=>setEf({...ef,invoice:v})} options={INVOICE_OPTIONS}/><Select label="Type of Pay" v={ef.pay} set={v=>setEf({...ef,pay:v})} options={PAYMENT_TYPES}/><Input label="Reference" v={ef.reference} set={v=>setEf({...ef,reference:v})}/><Input label="Note" v={ef.note} set={v=>setEf({...ef,note:v})}/></div><button className="mt-4 rounded bg-blue-700 px-5 py-2 font-bold text-white">Save Expense</button></form><Filters search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} options={["All",...EXPENSE_CATEGORIES]}/><Table headers={["Date","Type","Reason","Amount","Invoice","Pay Type","Note","Reference","Recorded By"]} rows={expenseRows} page={page} setPage={setPage} render={r=><tr key={r.id} className="border-t"><Cell>{r.expense_date}</Cell><Cell>{r.category}</Cell><Cell>{r.description}</Cell><Cell>{formatCurrency(r.amount)}</Cell><Cell>{r.invoice_option}</Cell><Cell>{r.payment_type}</Cell><Cell>{r.notes||"-"}</Cell><Cell>{r.reference||"-"}</Cell><Cell>{r.created_by||"-"}</Cell></tr>}/></>}
 {tab==="Payout"&&<><form onSubmit={e=>{e.preventDefault();save(()=>createPayout({payoutDate:pf.date,type:pf.type,paymentType:pf.pay,payeeName:pf.name,supplierId:pf.supplierId,payPeriod:pf.period,notes:pf.note,amount:pf.amount,status:pf.status},user()),()=>setPf({...pf,amount:"",note:"",period:"",name:""}))}} className="rounded-xl border bg-white p-4"><h3 className="mb-3 font-bold">Record Payout</h3><div className="grid gap-3 md:grid-cols-4"><Input label="Date" type="date" v={pf.date} set={v=>setPf({...pf,date:v})}/><Select label="Type of Payout" v={pf.type} set={v=>setPf({...pf,type:v})} options={PAYOUT_CATEGORIES}/><Select label="Type of Pay" v={pf.pay} set={v=>setPf({...pf,pay:v})} options={PAYMENT_TYPES}/>{pf.type==="Supplier Payout"?<SupplierSelect suppliers={suppliers} v={pf.supplierId} set={v=>setPf({...pf,supplierId:v})}/>:<Input label="Name" v={pf.name} set={v=>setPf({...pf,name:v})}/>}<Input label="Pay for Period" v={pf.period} set={v=>setPf({...pf,period:v})}/><Input label="Note" v={pf.note} set={v=>setPf({...pf,note:v})}/><Input label="Amount" type="number" v={pf.amount} set={v=>setPf({...pf,amount:v})}/><Select label="Status" v={pf.status} set={v=>setPf({...pf,status:v})} options={PAYOUT_STATUSES}/></div><button className="mt-4 rounded bg-blue-700 px-5 py-2 font-bold text-white">Save Payout</button></form><Filters search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} options={["All",...PAYOUT_STATUSES]}/><Table headers={["Date","Type","Pay Type","Name","Pay Period","Note","Amount","Status","Recorded By"]} rows={payoutRows} page={page} setPage={setPage} render={r=><tr key={r.id} className="border-t"><Cell>{r.payout_date}</Cell><Cell>{r.payout_type}</Cell><Cell>{r.payment_type}</Cell><Cell>{r.suppliers?.supplier_name||r.payee_name||"-"}</Cell><Cell>{r.pay_period||"-"}</Cell><Cell>{r.notes||"-"}</Cell><Cell>{formatCurrency(r.amount)}</Cell><Cell>{r.status}</Cell><Cell>{r.created_by||"-"}</Cell></tr>}/></>}
 {tab==="Direct Debit"&&<><form onSubmit={e=>{e.preventDefault();save(()=>createDirectDebit({name:df.name,supplierId:df.supplierId,amount:df.amount,frequency:df.frequency,nextDueDate:df.nextDueDate,paymentType:df.pay,accountReference:df.accountReference,whatsappNumber:df.whatsappNumber,reminderDaysBefore:df.reminderDaysBefore,notes:df.notes},user()),()=>setDf({...df,name:"",amount:"",accountReference:"",notes:""}))}} className="rounded-xl border bg-white p-4"><h3 className="mb-3 font-bold">Direct Debit Reminder</h3><div className="grid gap-3 md:grid-cols-4"><Input label="Payment Name" v={df.name} set={v=>setDf({...df,name:v})}/><SupplierSelect suppliers={suppliers} v={df.supplierId} set={v=>setDf({...df,supplierId:v})} optional/><Input label="Amount" type="number" v={df.amount} set={v=>setDf({...df,amount:v})}/><Select label="Frequency" v={df.frequency} set={v=>setDf({...df,frequency:v})} options={DIRECT_DEBIT_FREQUENCIES}/><Input label="Next Due Date" type="date" v={df.nextDueDate} set={v=>setDf({...df,nextDueDate:v})}/><Select label="Type of Pay" v={df.pay} set={v=>setDf({...df,pay:v})} options={PAYMENT_TYPES}/><Input label="Account Reference" v={df.accountReference} set={v=>setDf({...df,accountReference:v})}/><Input label="WhatsApp Number" v={df.whatsappNumber} set={v=>setDf({...df,whatsappNumber:v})}/><Input label="Reminder Days Before" type="number" v={df.reminderDaysBefore} set={v=>setDf({...df,reminderDaysBefore:v})}/><Input label="Notes" v={df.notes} set={v=>setDf({...df,notes:v})}/></div><button className="mt-4 rounded bg-blue-700 px-5 py-2 font-bold text-white">Save Reminder</button></form><Table headers={["Due Date","Name","Supplier","Amount","Frequency","Pay Type","WhatsApp","Reminder","Recorded By"]} rows={debits} page={page} setPage={setPage} render={r=><tr key={r.id} className="border-t"><Cell>{r.next_due_date}</Cell><Cell>{r.name}</Cell><Cell>{r.suppliers?.supplier_name||"-"}</Cell><Cell>{formatCurrency(r.amount)}</Cell><Cell>{r.frequency}</Cell><Cell>{r.payment_type}</Cell><Cell>{r.whatsapp_number}</Cell><Cell>{r.reminder_days_before} day(s) before</Cell><Cell>{r.created_by||"-"}</Cell></tr>}/></>}
 {tab==="Supplier Credit"&&<><div className="rounded-xl border bg-white p-4"><div className="grid gap-3 md:grid-cols-3"><SupplierSelect suppliers={suppliers} v={supplierId} set={chooseSupplier}/>{selected&&<><Info label="Address" v={selected.address}/><Info label="VAT Number" v={selected.vat_number}/><Info label="Contact Number" v={selected.contact_number||selected.phone}/><Info label="Email" v={selected.email}/><Info label="Contact Person" v={selected.contact_person||selected.contact_name}/></>}<Info label="Current Supplier Credit" v={formatCurrency(credit.balance)}/></div></div>{supplierId&&<form onSubmit={e=>{e.preventDefault();save(()=>createSupplierCreditTransaction({supplierId,transactionDate:cf.date,transactionType:cf.type,amount:cf.amount,invoiceNumber:cf.invoiceNumber,paymentType:cf.pay,reference:cf.reference,notes:cf.notes},user()),()=>setCf({...cf,amount:"",invoiceNumber:"",reference:"",notes:""}))}} className="rounded-xl border bg-white p-4"><h3 className="mb-3 font-bold">Record Supplier Credit Transaction</h3><div className="grid gap-3 md:grid-cols-4"><Input label="Date" type="date" v={cf.date} set={v=>setCf({...cf,date:v})}/><Select label="Transaction" v={cf.type} set={v=>setCf({...cf,type:v})} options={["Credit Purchase","Payment","Credit Note","Adjustment"]}/><Input label="Amount" type="number" v={cf.amount} set={v=>setCf({...cf,amount:v})}/><Input label="Invoice Number" v={cf.invoiceNumber} set={v=>setCf({...cf,invoiceNumber:v})}/><Select label="Type of Pay" v={cf.pay} set={v=>setCf({...cf,pay:v})} options={PAYMENT_TYPES}/><Input label="Reference" v={cf.reference} set={v=>setCf({...cf,reference:v})}/><Input label="Notes" v={cf.notes} set={v=>setCf({...cf,notes:v})}/></div><button className="mt-4 rounded bg-blue-700 px-5 py-2 font-bold text-white">Save Transaction</button></form>}<Table headers={["Date","Source","Transaction","Invoice","Reference","Credit Added","Payment/Credit Note","Balance"]} rows={credit.transactions} page={page} setPage={setPage} empty="Select a supplier to see its exact credit statement." render={(r,i)=><tr key={`${r.transaction_date}-${i}`} className="border-t"><Cell>{r.transaction_date}</Cell><Cell>{r.source}</Cell><Cell>{r.transaction_type}</Cell><Cell>{r.invoice_number||"-"}</Cell><Cell>{r.reference||"-"}</Cell><Cell>{formatCurrency(r.debit)}</Cell><Cell>{formatCurrency(r.credit)}</Cell><Cell>{formatCurrency(r.running_balance)}</Cell></tr>}/></>}
 </div></div>
}
function Input({label,type="text",v,set}){return <label className="text-xs font-bold">{label}<input required className={`${field} mt-1`} type={type} step={type==="number"?"0.01":undefined} value={v} onChange={e=>set(e.target.value)}/></label>}
function Select({label,v,set,options}){return <label className="text-xs font-bold">{label}<select className={`${field} mt-1`} value={v} onChange={e=>set(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select></label>}
function SupplierSelect({suppliers,v,set,optional=false}){return <label className="text-xs font-bold">Supplier<select required={!optional} className={`${field} mt-1`} value={v} onChange={e=>set(e.target.value)}><option value="">{optional?"Not applicable":"Select supplier"}</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.supplier_name}</option>)}</select></label>}
function Filters({search,setSearch,filter,setFilter,options}){return <div className="flex flex-col gap-2 rounded-xl border bg-white p-3 md:flex-row"><input className={field} placeholder="Search..." value={search} onChange={e=>setSearch(e.target.value)}/><select className={field} value={filter} onChange={e=>setFilter(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select></div>}
function Cell({children}){return <td className="p-2">{children}</td>}
function Info({label,v}){return <div className="rounded bg-slate-50 p-3 text-sm"><b>{label}:</b> {v||"-"}</div>}
