import { useEffect, useMemo, useState } from "react";
import { getCustomerAccounts } from "../../services/customerManagement";
import { loadRouteAssignments, loadSalesRouteStaff, removeRouteAssignment, saveRouteAssignment, SALES_ROUTE_DAYS } from "../../services/salesRouteService";

const PAGE_SIZE = 30;
const normalise = (value) => String(value || "").trim();
const customerCountry = (customer) => normalise(customer?.country || customer?.account_country || customer?.default_country || (customer?.customer_branches || []).find((b) => b?.active !== false)?.country) || "Unknown";

export default function SalesRouteSetup() {
  const [customers, setCustomers] = useState([]); const [staff, setStaff] = useState([]); const [routes, setRoutes] = useState([]);
  const [day, setDay] = useState("Monday"); const [country, setCountry] = useState("All"); const [customerId, setCustomerId] = useState(""); const [branchId, setBranchId] = useState(""); const [staffId, setStaffId] = useState(""); const [sequence, setSequence] = useState(1); const [search, setSearch] = useState(""); const [page, setPage] = useState(1); const [saving, setSaving] = useState(false);
  const load = async () => { const [c, s, r] = await Promise.all([getCustomerAccounts({ operationalOnly: true }), loadSalesRouteStaff(), loadRouteAssignments()]); setCustomers(c || []); setStaff(s || []); setRoutes(r || []); };
  useEffect(() => { void load(); }, []);
  const countries = useMemo(() => { const values = new Set(["Wales", "England"]); customers.forEach((c) => values.add(customerCountry(c))); return [...values].filter(Boolean).sort((a, b) => a.localeCompare(b)); }, [customers]);
  const selectableCustomers = useMemo(() => customers.filter((c) => country === "All" || customerCountry(c) === country), [customers, country]);
  const selected = customers.find((c) => String(c.id) === String(customerId));
  const branches = (selected?.customer_branches || []).filter((b) => b.active !== false && (country === "All" || !b.country || normalise(b.country) === country));
  const filtered = useMemo(() => routes.filter((r) => r.day_of_week === day).map((r) => ({ ...r, customer: customers.find((c) => String(c.id) === String(r.customer_account_id)), staff: staff.find((s) => String(s.id) === String(r.assigned_staff_id)) })).filter((r) => r.customer).filter((r) => country === "All" || customerCountry(r.customer) === country).filter((r) => !search || [r.customer?.account_name, r.customer?.town_city, r.customer?.postcode, customerCountry(r.customer), r.staff?.staff_name].some((v) => normalise(v).toLowerCase().includes(search.toLowerCase()))).sort((a, b) => Number(a.visit_sequence || 0) - Number(b.visit_sequence || 0)), [routes, customers, staff, day, country, search]);
  useEffect(() => { setPage(1); }, [day, country, search]);
  useEffect(() => { if (customerId && !selectableCustomers.some((c) => String(c.id) === String(customerId))) { setCustomerId(""); setBranchId(""); } }, [country, customerId, selectableCustomers]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const currentPage = Math.min(page, pageCount); const visibleRows = filtered.slice((currentPage - 1) * PAGE_SIZE, currentPage * PAGE_SIZE);
  const save = async () => { if (!customerId) return alert("Select customer."); setSaving(true); try { await saveRouteAssignment({ customerAccountId: customerId, customerBranchId: branchId || null, assignedStaffId: staffId || null, dayOfWeek: day, visitSequence: sequence }); setCustomerId(""); setBranchId(""); setSequence(filtered.length + 2); await load(); } catch (e) { alert(e.message || "Could not save route."); } finally { setSaving(false); } };

  return <div className="p-4 space-y-4">
    <div><h2 className="text-2xl font-bold">Sales Route Setup</h2><p className="text-sm text-slate-500">Assign customers to a permanent weekday route. Countries are read from customer data, so future countries appear automatically.</p></div>
    <div className="flex flex-wrap gap-2">{SALES_ROUTE_DAYS.map((d) => <button key={d} onClick={() => setDay(d)} className={`px-4 py-2 rounded-xl font-bold ${day === d ? "bg-blue-950 text-white" : "bg-white border"}`}>{d}</button>)}</div>
    <div className="grid md:grid-cols-6 gap-3 bg-white border rounded-2xl p-4">
      <label className="text-sm font-bold">Country<select className="mt-1 w-full border rounded-xl p-2" value={country} onChange={(e) => setCountry(e.target.value)}><option value="All">All countries</option>{countries.map((c) => <option key={c} value={c}>{c}</option>)}</select></label>
      <label className="text-sm font-bold">Customer<select className="mt-1 w-full border rounded-xl p-2" value={customerId} onChange={(e) => { setCustomerId(e.target.value); setBranchId(""); }}><option value="">Select customer</option>{selectableCustomers.map((c) => <option key={c.id} value={c.id}>{c.account_name}</option>)}</select></label>
      <label className="text-sm font-bold">Branch<select className="mt-1 w-full border rounded-xl p-2" value={branchId} onChange={(e) => setBranchId(e.target.value)}><option value="">Main / no branch</option>{branches.map((b) => <option key={b.id} value={b.id}>{b.branch_name}</option>)}</select></label>
      <label className="text-sm font-bold">Sales Rep<select className="mt-1 w-full border rounded-xl p-2" value={staffId} onChange={(e) => setStaffId(e.target.value)}><option value="">Any authorised rep</option>{staff.map((s) => <option key={s.id} value={s.id}>{s.staff_name}</option>)}</select></label>
      <label className="text-sm font-bold">Visit order<input type="number" min="1" className="mt-1 w-full border rounded-xl p-2" value={sequence} onChange={(e) => setSequence(e.target.value)} /></label>
      <div className="flex items-end"><button disabled={saving} onClick={save} className="w-full rounded-xl bg-emerald-600 text-white p-2 font-bold">{saving ? "Saving..." : "Add to Route"}</button></div>
    </div>
    <div className="bg-white border rounded-2xl overflow-hidden"><div className="p-3 flex flex-wrap items-center justify-between gap-3"><strong>{day} Route · {filtered.length} customers{country !== "All" ? ` · ${country}` : ""}</strong><input className="border rounded-lg px-3 py-2" placeholder="Search route" value={search} onChange={(e) => setSearch(e.target.value)} /></div><div className="overflow-auto"><table className="w-full text-sm"><thead className="bg-slate-100"><tr><th className="p-2 text-left">#</th><th className="p-2 text-left">Customer</th><th className="p-2 text-left">Branch</th><th className="p-2 text-left">Country</th><th className="p-2 text-left">Location</th><th className="p-2 text-left">Sales Rep</th><th className="p-2"></th></tr></thead><tbody>{visibleRows.map((r) => { const b = (r.customer?.customer_branches || []).find((x) => String(x.id) === String(r.customer_branch_id)); return <tr key={r.id} className="border-t"><td className="p-2">{r.visit_sequence}</td><td className="p-2 font-bold">{r.customer?.account_name || "Unknown"}</td><td className="p-2">{b?.branch_name || "Main"}</td><td className="p-2">{b?.country || customerCountry(r.customer)}</td><td className="p-2">{b?.postcode || r.customer?.postcode || r.customer?.town_city || "—"}</td><td className="p-2">{r.staff?.staff_name || "Any rep"}</td><td className="p-2 text-right"><button onClick={async () => { if (confirm("Remove this customer from the route?")) { await removeRouteAssignment(r.id); await load(); } }} className="text-red-700 font-bold">Remove</button></td></tr>; })}{!visibleRows.length && <tr><td colSpan="7" className="p-8 text-center text-slate-500">No customers assigned to this selection.</td></tr>}</tbody></table></div><div className="flex flex-wrap items-center gap-2 border-t p-3 text-sm"><span className="mr-auto text-slate-500">Showing {filtered.length ? (currentPage - 1) * PAGE_SIZE + 1 : 0}–{Math.min(currentPage * PAGE_SIZE, filtered.length)} of {filtered.length} · max 30 per page</span><button className="border rounded-lg px-3 py-1 disabled:opacity-40" disabled={currentPage <= 1} onClick={() => setPage((p) => Math.max(1, p - 1))}>Previous</button><span className="font-bold">Page {currentPage} / {pageCount}</span><button className="border rounded-lg px-3 py-1 disabled:opacity-40" disabled={currentPage >= pageCount} onClick={() => setPage((p) => Math.min(pageCount, p + 1))}>Next</button></div></div>
  </div>;
}
