export const FC_PERMISSIONS = Object.freeze({
  ALL_ACCESS: "all_access",
  PAGE_SALES_REP: "page.sales_rep",
  PAGE_WAREHOUSE: "page.warehouse",
  PAGE_PRODUCT_SETUP: "page.product_setup",
  PAGE_CUSTOMER_CREDIT: "page.customer_credit",
  PAGE_SUPPLIER_ACCOUNTS: "page.supplier_accounts",
  ORDERS_TAKE: "orders.take",
  ORDERS_VIEW_ALL: "orders.view_all",
  ORDERS_EDIT: "orders.edit",
  ORDERS_CANCEL: "orders.cancel",
  WAREHOUSE_PICK: "warehouse.pick",
  WAREHOUSE_PACK: "warehouse.pack",
  WAREHOUSE_COMPLETE: "warehouse.complete",
  DELIVERY_COMPLETE: "delivery.complete",
  CUSTOMERS_CREDIT_CHECK: "customers.credit_check",
  CUSTOMERS_CREATE_LOGIN: "customers.create_login",
  CUSTOMERS_EDIT: "customers.edit",
  PRODUCTS_SETUP: "products.setup",
  PAYMENTS_COLLECT_CASH: "payments.collect_cash",
  PAYMENTS_COLLECT_CARD: "payments.collect_card",
  PAYMENTS_VIEW: "payments.view",
  PAYMENTS_VOID: "payments.void",
  CUSTOMER_CREDIT_PAYMENT_EDIT: "customer_credit.payment_edit",
  CUSTOMER_CREDIT_PAYMENT_DELETE: "customer_credit.payment_delete",
  CUSTOMER_CREDIT_PAYMENT_VOID: "customer_credit.payment_void",
  CUSTOMER_CREDIT_VIEW: "customer_credit.view",
  CUSTOMER_CREDIT_PAYMENT_VIEW: "customer_credit.payment_view",
  CUSTOMER_CREDIT_OPENING_BALANCE_EDIT:
    "customer_credit.opening_balance_edit",
  CUSTOMER_CREDIT_AUDIT_VIEW: "customer_credit.audit_view",
  SUPPLIERS_VIEW: "suppliers.view",
  SUPPLIERS_PAY: "suppliers.pay",
  EXPENSES_VIEW: "expenses.view",
  EXPENSES_CREATE: "expenses.create",
  EXPENSES_SUBMIT: "expenses.submit",
  EXPENSES_APPROVE: "expenses.approve",
  EXPENSES_VOID: "expenses.void",
  RETURNS_VIEW: "returns.view",
  RETURNS_APPROVE: "returns.approve",
  RETURNS_REVERSE: "returns.reverse",
  RETURNS_RECONCILE: "returns.reconcile",
  STAFF_MANAGE: "staff.manage",
  PERMISSIONS_MANAGE: "permissions.manage",
});

export function hasFcPermission(user, permissionKey) {
  const permissions = user?.effective_permissions || user?.permissions || {};
  return permissions.all_access === true || permissions[permissionKey] === true;
}
